name: Deploy to Aws Socker on merge
'on':
  push:
    branches:
      - prod-docker

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mirrorml/se331-2022-project-frontend-1:latest
